//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationProjetoAula5
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPRA
    {
        public int id { get; set; }
        public Nullable<int> id_fornecedor { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_material { get; set; }
        public Nullable<System.DateTime> datavenda { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual FORNECEDOR FORNECEDOR { get; set; }
        public virtual MATERIAL MATERIAL { get; set; }
    }
}
