//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationProjetoAula5
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATERIAL()
        {
            this.COMPRA = new HashSet<COMPRA>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public Nullable<System.DateTime> dataentrada { get; set; }
        public Nullable<int> id_tipo { get; set; }
        public Nullable<int> id_fornecedor { get; set; }
        public Nullable<decimal> valor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMPRA> COMPRA { get; set; }
        public virtual FORNECEDOR FORNECEDOR { get; set; }
        public virtual TIPO TIPO { get; set; }
    }
}
