//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjEmpresaWCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CADASTRO
    {
        public int ID { get; set; }
        public string NOME { get; set; }
        public Nullable<int> QTDFUNCIONARIOS { get; set; }
        public string ENDERECO { get; set; }
    }
}
