//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTarefa
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PROJETO
    {
        public int id { get; set; }
        public string descricao { get; set; }
        public Nullable<System.DateTime> dtiniprojeto { get; set; }
        public Nullable<System.DateTime> dtimplantado { get; set; }
        public Nullable<System.DateTime> dtteste { get; set; }
        public Nullable<int> qtdpessoas { get; set; }
        public string contatotel1 { get; set; }
        public string contatotel2 { get; set; }
        public string observacao { get; set; }
    }
}
